<?xml version='1.0'?>

<robot name="ottobot" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- SUB-COMPONENTS -->
    <xacro:include filename="$(find ottobot_description)/urdf/ottobot_wheel.urdf.xacro" />
    <xacro:include filename="$(find ottobot_description)/urdf/bno055imu.urdf.xacro" />
    <xacro:arg name="enable_kinect" default="false" />
    <xacro:if value="$(arg enable_kinect)">
        <xacro:include filename="$(find ottobot_description)/urdf/kinect.urdf.xacro" />
    </xacro:if>
    <xacro:arg name="enable_lidar" default="false" />
    <xacro:if value="$(arg enable_lidar)">
        <xacro:include filename="$(find ottobot_description)/urdf/a1rplidar.urdf.xacro" />
    </xacro:if>

    <!-- PROPERTIES -->
    <xacro:property name="M_PI"   value="3.141592653"/>
    <xacro:property name="M_2_PI" value="6.283185307"/>
    <xacro:property name="M_PI_2" value="1.570796326"/>

    <xacro:property name="parent" value="robot_footprint" />

    <xacro:property name="chassis_mass" value="2.0" />
    <xacro:property name="chassis_height" value="0.095" />
    <xacro:property name="chassis_length" value="0.23" />
    <xacro:property name="chassis_width" value="0.12" />
    <xacro:property name="chassis_gnd_clearance" value="0.05" />

    <xacro:property name="wheel_mass" value="0.186" />
    <xacro:property name="wheel_width" value="0.062" />
    <xacro:property name="wheel_rad" value="0.064" />
    <xacro:property name="wheel_forward_offset" value="0.075" />
    <xacro:property name="wheel_left_offset" value="0.125" />
    <xacro:property name="wheel_vert_offset" value="${-chassis_gnd_clearance - chassis_height/2 + wheel_rad}" />

    <!-- IMU pose -->
    <xacro:property name="imu_px" value="-0.032" />
	<xacro:property name="imu_py" value="-0.035" />
	<xacro:property name="imu_pz" value="${0.039 + chassis_height/2}" />
	<xacro:property name="imu_or" value="0" />
	<xacro:property name="imu_op" value="0" />
	<xacro:property name="imu_oy" value="${M_PI}" />

    <!-- Kinect pose -->
    <xacro:property name="cam_px" value="${chassis_length / 2}" />
	<xacro:property name="cam_py" value="0" />
	<xacro:property name="cam_pz" value="${0.05 + chassis_height/2}" />
	<xacro:property name="cam_or" value="0" />
	<xacro:property name="cam_op" value="0" />
	<xacro:property name="cam_oy" value="0" />

    <!-- A1 Lidar pose -->
    <xacro:property name="lidar_px" value="0.06" />
	<xacro:property name="lidar_py" value="0" />
	<xacro:property name="lidar_pz" value="${0.012 + chassis_height/2}" />
	<xacro:property name="lidar_or" value="0" />
	<xacro:property name="lidar_op" value="0" />
	<xacro:property name="lidar_oy" value="${M_PI}" />
    
    <!-- PLUGINS -->
    <xacro:include filename="$(find ottobot_description)/urdf/ottobot.gazebo.xacro" />

    <!-- PARTS -->
    <link name="${parent}"></link>

    <joint name="${parent}_joint" type="fixed">
        <origin xyz="0 0 ${chassis_gnd_clearance + chassis_height/2}" rpy="0 0 0" />
        <parent link="${parent}"/>
        <child link="chassis" />
    </joint>

    <link name='chassis'>
        <!-- <pose>0 0 0.1 0 0 0</pose> -->

        <inertial>
            <mass value="${chassis_mass}"/>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <inertia    ixx="${1/12 * chassis_mass * (chassis_height**2 + chassis_width**2)}"
                        ixy="0"
                        ixz="0"
                        iyy="${1/12 * chassis_mass * (chassis_height**2 + chassis_length**2)}"
                        iyz="0"
                        izz="${1/12 * chassis_mass * (chassis_length**2 + chassis_width**2)}" />
        </inertial>

        <collision name='collision'>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <visual name='chassis_visual'>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
    </link>

    <!-- WHEELS - - - - - - - - -->
    <!-- Format from https://github.com/husky/husky/blob/melodic-devel/husky_description/urdf/husky.urdf.xacro -->
    <xacro:ottobot_wheel wheel_prefix="front_left">
        <origin xyz="${wheel_forward_offset} ${wheel_left_offset} ${wheel_vert_offset}" rpy="0 0 0" />
    </xacro:ottobot_wheel>
    <xacro:ottobot_wheel wheel_prefix="front_right">
        <origin xyz="${wheel_forward_offset} -${wheel_left_offset} ${wheel_vert_offset}" rpy="0 0 0" />
    </xacro:ottobot_wheel>
    <xacro:ottobot_wheel wheel_prefix="back_left">
        <origin xyz="-${wheel_forward_offset} ${wheel_left_offset} ${wheel_vert_offset}" rpy="0 0 0" />
    </xacro:ottobot_wheel>
    <xacro:ottobot_wheel wheel_prefix="back_right">
        <origin xyz="-${wheel_forward_offset} -${wheel_left_offset} ${wheel_vert_offset}" rpy="0 0 0" />
    </xacro:ottobot_wheel>


    <!-- SENSORS - - - - - - - - -->
    <xacro:sensor_imu parent="chassis"></xacro:sensor_imu>

    <xacro:if value="$(arg enable_kinect)">
        <xacro:sensor_kinect parent="chassis"></xacro:sensor_kinect>
    </xacro:if>

    <xacro:if value="$(arg enable_lidar)">
        <xacro:sensor_lidar parent="chassis"></xacro:sensor_lidar>
    </xacro:if>

    <!-- COLORS - - - - - - - - -->
    <gazebo reference="left_wheel">
        <material>Gazebo/Turquoise</material>
    </gazebo>
    <gazebo reference="right_wheel">
        <material>Gazebo/Turquoise</material>
    </gazebo>
    <gazebo reference="chassis">
        <material>Gazebo/SkyBlue</material>
    </gazebo>
</robot>
