global_costmap:
  global_frame: map
  static_map: false  # Determines whether or not the costmap should initialize itself based on a map served by the map_server
  rolling_window: false  # If the static_map parameter is set to true, this parameter must be set to false.