global_costmap:
   update_frequency: 2.0  # Default: 5.0 Hz
   publish_frequency: 2.0  # Default: 0 Hz
   width: 10.0
   height: 10.0
   origin_x: 5.0
   origin_y: 5.0
   resolution: 0.05
   inflation_radius: 0.3  # Default: 0.55 m
   cost_scaling_factor: 8.0  # Default: 10.0 (5 used)
