local_costmap:
   global_frame: odom #map
   update_frequency: 5.0  # Default: 5.0 Hz
   publish_frequency: 5.0 # Default: 0 Hz
   width: 5.0
   height: 5.0
   resolution: 0.05
   static_map: false
   rolling_window: true

   inflation_radius: 0.10  # Default: 0.55 m
   cost_scaling_factor: 5.0  # Default: 10.0 (5 used)
